### ISSUE TITLE
PHP 8.x support

### ISSUE THREAD

**Issue by jmecahansen** [tuupola/base85#20]
Hi,

Any plans to upgrade this package for it to be used with PHP 8.x? I cloned the repository and tried to modify the composer.json dependencies but it's not that simple if I want to properly test the package (phpbench doesn't run on PHP 8 either) although it works with the same examples in the [Usage](https://github.com/tuupola/base85#usage) section.

Any change to publish an update? :)

**Comment by tuupola** [comment]
It seems I have just forgotten to do it. I will try to fix this soonish.

**Comment by tuupola** [comment]
Released as [2.0.0](https://packagist.org/packages/tuupola/base85) which has PHP 8 support.
